// TAKE THE EVERY WORD FROM THE TEXT STRING WHENEVER A USER A WILL POST A TWEET AND WILL SORT EVERY WORD WHICH WILL START FRM '#'.
// AFTER SORTING THOSE WORDS, ON A SMALL SCALE WITHOUT CONSIDERING THE GEOGRAPHICAL LOCATION OF A USER, WE CAN SIMPLY JUST COUNT AND IF THAT COUNT INCREASE FROM 10 WE WE WILL ADD IT IN TO THE TRENDING BAR.
